name: todo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^0.1.3
  get:
  get_storage:
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lists.jpeg
